import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from 'next/link';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Users Explorer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-gray-50 text-gray-900">
        <nav className="bg-gray-900 px-6 py-4 flex gap-6 items-center">
          <Link href='/' className="text-white hover:text-gray-300">Home</Link>
          <Link href='/about' className="text-white hover:text-gray-300">About</Link>
          <Link href='/users' className="text-white hover:text-gray-300">Users</Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
